-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN ICECREAM_INFO ON ICECREAM_INFO.FLAVOR = F.FLAVOR
WHERE F.TOTAL_ORDER >= 3000 AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC