-- 코드를 입력하세요
SELECT U.TITLE,	U.BOARD_ID,	R.REPLY_ID,	R.WRITER_ID, R.CONTENTS, 
        DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD U
JOIN USED_GOODS_REPLY R ON R.BOARD_ID = U.BOARD_ID
WHERE U.CREATED_DATE LIKE '%2022-10-%'
ORDER BY R.CREATED_DATE asc, U.TITLE asc